FROM node:20-alpine as development

WORKDIR /app

COPY package*.json ./
RUN npm install && chown -R node:node /app/node_modules

COPY . .

USER node

EXPOSE 3000

CMD ["npm", "run", "dev"]